#! /usr/bin/env python2
import os
import sys
import md5
def indexfile(dbfile, infile):
  filehash = md5.md5(infile).hexdigest()
  hashes = dbfile.read().split("\n")
  if filehash in hashes:
    print("File already indexed")
  else:
    dbfile.write(filehash + "\n")
    print("Cached: " + filehash)
if len(sys.argv) > 1:
  if os.path.isfile(sys.argv[1]):
    indexfile(open('database', 'r+a'), open(sys.argv[1]).read())
    print("Are you sure? [Y/n]"),
    uc = raw_input()
    if uc in ['y', 'Y', 'yes' ]:
      os.remove(sys.argv[1])
      print('Deleted')
    else:
      print('Canceled')
  elif sys.argv[1] == "--clear" or sys.argv[1] == "-c":
    open('database', 'w').write("")
  else:
    print("File not found: " + sys.argv[1])
else:
  print("Usage:\nrcl [-c] <filename>")
